import React,{useState,useEffect,useRef} from 'react';
import {Alert,Image,Pressable,ScrollView,Share,StyleSheet,Text,TextInput,View} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as ImagePicker from 'expo-image-picker';
import * as FileSystem from 'expo-file-system/legacy';
import {calculate,currencies,panels,toDisplay,toMetres,vinyls} from './src/domain';
const tabs=['Dashboard','New Wrap','Visualiser','Calculator','Vinyl Library','Customers','Quotes','Jobs','Stock','Reports','Settings','Beta Feedback'];
const initial=()=>({company:'WeWrap Studio',currency:'ZAR',unit:'metric',rates:{...currencies},draft:{vehicle:'Volkswagen Golf',customer:'',vinyl:'v1',rollWidth:1.52,waste:15,price:520,hours:18,rate:250,markup:40,panels:panels(),photo:null},customers:[],quotes:[],jobs:[],stock:vinyls.map(v=>({id:v.id,metres:v.stock})),feedback:[]});
const Button=({title,onPress})=><Pressable accessibilityRole="button" style={st.button} onPress={onPress}><Text style={st.buttonText}>{title}</Text></Pressable>;
const Field=({label,value,onChange,numeric})=><View style={st.field}><Text style={st.label}>{label}</Text><TextInput accessibilityLabel={label} style={st.input} value={String(value)} onChangeText={onChange} keyboardType={numeric?'decimal-pad':'default'}/></View>;
export default function App(){const [s,set]=useState(initial),[page,go]=useState('Dashboard'),[ready,readySet]=useState(false),[name,nameSet]=useState(''),[email,emailSet]=useState(''),[note,noteSet]=useState(''),[qid,qSet]=useState(null);const writes=useRef(Promise.resolve());
useEffect(()=>{AsyncStorage.getItem('wewrap-native-v1').then(raw=>{if(raw){const data=JSON.parse(raw);calculate(data.draft);set(data);}readySet(true);}).catch(()=>Alert.alert('Storage recovery needed','Saved records could not be loaded. They have not been overwritten.'));},[]);
useEffect(()=>{if(ready){const snapshot=JSON.stringify(s);writes.current=writes.current.then(()=>AsyncStorage.setItem('wewrap-native-v1',snapshot)).catch(()=>Alert.alert('Save failed','Export a backup before closing.'));}},[s,ready]);
const patch=(k,v)=>set(x=>({...x,[k]:v})),draft=(k,v)=>set(x=>({...x,draft:{...x.draft,[k]:v}})),v=vinyls.find(v=>v.id===s.draft.vinyl),u=s.unit==='metric'?'m':'ft',measure=n=>toDisplay(n,s.unit).toFixed(2),money=(n,c=s.currency,r=s.rates[c])=>new Intl.NumberFormat('en',{style:'currency',currency:c}).format(n*r);let t;try{t=calculate(s.draft);}catch{t=null;}
function num(label,key,length=false){return <Field label={label} value={length?measure(s.draft[key]):s.draft[key]} numeric onChange={text=>{const n=Number(text.replace(',','.'));if(Number.isFinite(n)&&n>=0)draft(key,length?toMetres(n,s.unit):n);}}/>;}
const row=(k,val)=><View key={k} style={st.row}><Text style={st.label}>{k}</Text><Text style={st.text}>{val}</Text></View>;
function material(m){set(x=>({...x,draft:{...x.draft,vinyl:m.id,price:m.price}}));}
async function photo(camera){try{const permission=await(camera?ImagePicker.requestCameraPermissionsAsync():ImagePicker.requestMediaLibraryPermissionsAsync());if(!permission.granted)return Alert.alert('Permission required','Allow photo access to select a vehicle.');const result=await(camera?ImagePicker.launchCameraAsync:ImagePicker.launchImageLibraryAsync)({mediaTypes:['images'],quality:.6});if(!result.canceled){const target=FileSystem.documentDirectory+'vehicle-'+Date.now()+'.jpg';await FileSystem.copyAsync({from:result.assets[0].uri,to:target});draft('photo',target);}}catch{Alert.alert('Photo unavailable','Try a different image or check permissions.');}}
const preview=()=> <View style={st.preview}>{s.draft.photo?<><Image source={{uri:s.draft.photo}} style={st.photo}/><View pointerEvents="none" style={[StyleSheet.absoluteFillObject,{backgroundColor:v.color,opacity:.14}]}/></>:<Text style={st.text}>Upload a vehicle photo to start</Text>}<Text style={st.caption}>COLOUR CONCEPT · {v.finish}</Text></View>;
function quote(){if(!t?.valid)return Alert.alert('Check dimensions','Enter a positive roll width and panels that fit.');const c=s.customers.find(c=>c.id===s.draft.customer);if(!c){go('Customers');return Alert.alert('Choose a customer','Add or select a customer before saving.');}const q={id:'WW-'+Date.now(),customer:c.name,vehicle:s.draft.vehicle,material:v.name,brand:v.brand,finish:v.finish,totals:t,currency:s.currency,rate:s.rates[s.currency],photo:s.draft.photo,date:new Date().toISOString()};patch('quotes',[...s.quotes,q]);qSet(q.id);go('Quotes');}
async function backup(){try{const data=JSON.parse(JSON.stringify(s));const embed=async uri=>uri?'data:image/jpeg;base64,'+await FileSystem.readAsStringAsync(uri,{encoding:'base64'}):null;data.draft.photo=await embed(data.draft.photo);for(const q of data.quotes)q.photo=await embed(q.photo);const file=FileSystem.cacheDirectory+'wewrap-backup.json';await FileSystem.writeAsStringAsync(file,JSON.stringify(data));const Sharing=await import('expo-sharing');if(await Sharing.isAvailableAsync())await Sharing.shareAsync(file,{mimeType:'application/json'});else await Share.share({message:JSON.stringify(data)});}catch{Alert.alert('Backup failed','Retry before clearing app data.');}}
async function restore(){try{const Picker=await import('expo-document-picker');const result=await Picker.getDocumentAsync({type:'application/json',copyToCacheDirectory:true});if(result.canceled)return;const data=JSON.parse(await FileSystem.readAsStringAsync(result.assets[0].uri));calculate(data.draft);if(!currencies[data.currency]||!['metric','imperial'].includes(data.unit)||!vinyls.some(v=>v.id===data.draft.vinyl)||!['customers','quotes','jobs','stock','feedback'].every(k=>Array.isArray(data[k])))throw Error();for(const k of Object.keys(currencies))if(!Number.isFinite(data.rates[k])||data.rates[k]<=0)throw Error();Alert.alert('Replace local records?','Export your current backup first.',[{text:'Cancel',style:'cancel'},{text:'Restore',onPress:async()=>{try{async function unpack(img){if(!img)return null;if(!/^data:image\/jpeg;base64,/.test(img))throw Error();const uri=FileSystem.documentDirectory+'restored-'+Date.now()+'-'+Math.random()+'.jpg';await FileSystem.writeAsStringAsync(uri,img.split(',')[1],{encoding:'base64'});return uri;}data.draft.photo=await unpack(data.draft.photo);for(const q of data.quotes)q.photo=await unpack(q.photo);set(data);}catch{Alert.alert('Invalid image backup','Current records kept.');}}}]);}catch{Alert.alert('Invalid mobile backup','Current records kept. Browser backups use a different format.');}}
function content(){switch(page){case 'Dashboard':return <><View style={st.hero}><Text style={st.eyebrow}>BUILT FOR YOUR WRAP SHOP</Text><Text style={st.heroTitle}>Every surface.\nA new possibility.</Text><Text style={st.graffiti}>WRAP / CREATE / REPEAT</Text><Button title="＋ Start a wrap" onPress={()=>go('New Wrap')}/></View>{row('Quoted pipeline',money(s.quotes.reduce((n,q)=>n+q.totals.sell,0)))}{row('Active jobs',s.jobs.filter(j=>j.status!=='Complete').length)}{row('Customers',s.customers.length)}<Text style={st.note}>Local phone storage. Export backups regularly.</Text></>;
case 'New Wrap':return <><Field label="Vehicle / year" value={s.draft.vehicle} onChange={x=>draft('vehicle',x)}/><Text style={st.title}>Choose customer</Text>{s.customers.map(c=><Button key={c.id} title={(s.draft.customer===c.id?'✓ ':'')+c.name} onPress={()=>draft('customer',c.id)}/>)}<Button title="Add customer" onPress={()=>go('Customers')}/>{preview()}<Button title="Upload photo" onPress={()=>photo(false)}/><Button title="Take photo" onPress={()=>photo(true)}/><Button title="Choose wrap →" onPress={()=>go('Visualiser')}/></>;
case 'Visualiser':return <>{preview()}<Text style={st.note}>Colour concept tint affects the whole photo. No AI segmentation or supplier colour matching.</Text>{vinyls.map(m=><Pressable key={m.id} onPress={()=>material(m)} style={[st.card,m.id===v.id&&{borderColor:'#c7f95c'}]}><View style={[st.swatch,{backgroundColor:m.color}]}/><Text style={st.text}>{m.brand} · {m.name} · {m.finish}</Text></Pressable>)}<Button title="Calculate wrap →" onPress={()=>go('Calculator')}/></>;
case 'Calculator':return <><Text style={st.note}>Independent cuts, rotatable 90°. Include fitting allowances. No nesting, seams or stretch assumed.</Text>{num('Roll width ('+u+')','rollWidth',true)}{num('Waste (%)','waste')}{num('Material per linear metre (ZAR)','price')}{s.draft.panels.map((p,i)=><View key={p.name} style={st.card}><Text style={st.title}>{p.name}</Text>{['length','width','qty'].map(k=><Field key={k} label={k==='qty'?'Quantity':k+' ('+u+')'} value={k==='qty'?p[k]:measure(p[k])} numeric onChange={text=>{const n=Number(text.replace(',','.'));if(!Number.isFinite(n)||n<0||(k==='qty'&&!Number.isInteger(n)))return;draft('panels',s.draft.panels.map((x,j)=>j===i?{...x,[k]:k==='qty'?n:toMetres(n,s.unit)}:x));}}/>)}<Text style={st.label}>{t?.rows[i].fits?measure(t.rows[i].metres)+' '+u+' allocated':'Does not fit roll'}</Text></View>)}{num('Labour hours','hours')}{num('Hourly rate (ZAR)','rate')}{num('Markup on cost (%)','markup')}{t?<>{row('Material with waste',measure(t.total)+' '+u)}{row('Material',money(t.material))}{row('Labour',money(t.labour))}{row('Profit',money(t.profit))}{row('Gross margin',t.margin.toFixed(1)+'%')}{row('Quote excluding tax',money(t.sell))}<Button title="Save customer quote" onPress={quote}/></>:<Text style={st.note}>Enter a positive roll width.</Text>}</>;
case 'Vinyl Library':return <><Text style={st.note}>Illustrative supplier catalogue and prices. Verify before production.</Text>{vinyls.map(m=><View key={m.id} style={st.card}><View style={[st.swatch,{backgroundColor:m.color}]}/><Text style={st.title}>{m.brand}</Text><Text style={st.text}>{m.name} · {m.finish}</Text>{row('Price / m',money(m.price))}<Button title="Use vinyl" onPress={()=>{material(m);go('Visualiser');}}/></View>)}</>;
case 'Customers':return <><Field label="Customer name" value={name} onChange={nameSet}/><Field label="Email" value={email} onChange={emailSet}/><Button title="Save customer" onPress={()=>{if(!name.trim())return;const c={id:String(Date.now()),name:name.trim(),email:email.trim()};set(x=>({...x,customers:[...x.customers,c],draft:{...x.draft,customer:c.id}}));nameSet('');emailSet('');}}/>{s.customers.map(c=><Button key={c.id} title={c.name+' · '+c.email} onPress={()=>{draft('customer',c.id);go('New Wrap');}}/>)}</>;
case 'Quotes':{const q=s.quotes.find(q=>q.id===qid);return <>{s.quotes.map(q=><Button key={q.id} title={q.customer+' · '+money(q.totals.sell,q.currency,q.rate)} onPress={()=>qSet(q.id)}/>)}{q&&<View style={st.card}><Text style={st.title}>{q.id}</Text><Text style={st.text}>{q.customer} · {q.vehicle}</Text><Text style={st.note}>{q.brand} / {q.material} / {q.finish}</Text>{q.photo&&<Image source={{uri:q.photo}} style={st.photo}/ >}{row('Quote excluding tax',money(q.totals.sell,q.currency,q.rate))}<Text style={st.note}>Saved currency/rate locked. Subject to vehicle inspection and verified supplier pricing.</Text><Button title="Share customer quote" onPress={()=>Share.share({message:`${s.company}\n${q.id}\n${q.customer} · ${q.vehicle}\n${q.brand} / ${q.material} / ${q.finish}\nQuote excluding tax: ${money(q.totals.sell,q.currency,q.rate)}\nSubject to inspection and verified supplier prices. Preview is a colour concept.`})}/><Button title="Create job" onPress={()=>{if(s.jobs.some(j=>j.quoteId===q.id))return Alert.alert('Job already exists');patch('jobs',[...s.jobs,{id:'JOB-'+Date.now(),quoteId:q.id,vehicle:q.vehicle,customer:q.customer,status:'Scheduled'}]);go('Jobs');}}/></View>}{!s.quotes.length&&<Text style={st.note}>Save a quote from Calculator.</Text>}</>;}
case 'Jobs':return <>{s.jobs.map(j=><View key={j.id} style={st.card}><Text style={st.title}>{j.vehicle}</Text><Text style={st.text}>{j.customer} · {j.status}</Text>{['Scheduled','Preparation','Wrapping','Quality check','Complete'].map(stage=><Button key={stage} title={(j.status===stage?'✓ ':'')+stage} onPress={()=>patch('jobs',s.jobs.map(x=>x.id===j.id?{...x,status:stage}:x))}/>)}</View>)}{!s.jobs.length&&<Text style={st.note}>Create a job from a quote.</Text>}</>;
case 'Stock':return <><Text style={st.note}>Manual ledger. Jobs do not automatically deduct stock.</Text>{s.stock.map(item=><Field key={item.id} label={vinyls.find(v=>v.id===item.id).brand+' on hand ('+u+')'} value={measure(item.metres)} numeric onChange={text=>{const n=Number(text.replace(',','.'));if(Number.isFinite(n)&&n>=0)patch('stock',s.stock.map(x=>x.id===item.id?{...x,metres:toMetres(n,s.unit)}:x));}}/>)}</>;
case 'Reports':return <>{['material','labour','profit','sell'].map(k=>row(k,money(s.quotes.reduce((n,q)=>n+q.totals[k],0))))}<Text style={st.note}>Quote projections, not invoiced revenue.</Text><Button title="Export backup" onPress={backup}/></>;
case 'Settings':return <><Field label="Studio name" value={s.company} onChange={x=>patch('company',x)}/><Text style={st.title}>Currency</Text>{Object.keys(currencies).map(c=><Button key={c} title={(s.currency===c?'✓ ':'')+c} onPress={()=>patch('currency',c)}/>)}<Text style={st.title}>Measurements</Text>{['metric','imperial'].map(u=><Button key={u} title={(s.unit===u?'✓ ':'')+u} onPress={()=>patch('unit',u)}/>)}<Text style={st.note}>Manual illustrative exchange rates, currency units per ZAR.</Text>{Object.keys(currencies).filter(c=>c!=='ZAR').map(c=><Field key={c} label={c+' per ZAR'} value={s.rates[c]} numeric onChange={text=>{const n=Number(text.replace(',','.'));if(n>0&&Number.isFinite(n))patch('rates',{...s.rates,[c]:n});}}/>)}<Button title="Export private backup" onPress={backup}/><Button title="Restore mobile backup" onPress={restore}/><Text style={st.note}>Mobile backups differ from browser backups. No login, cloud sync or real AI connected.</Text></>;
case 'Beta Feedback':return <><Field label="What happened? What should change?" value={note} onChange={noteSet}/><Button title="Save feedback" onPress={()=>{if(note.trim().length<10)return Alert.alert('Add details','Use at least 10 characters.');patch('feedback',[...s.feedback,{id:Date.now(),detail:note.trim(),date:new Date().toISOString()}]);noteSet('');}}/><Button title="Share feedback" onPress={()=>Share.share({message:JSON.stringify(s.feedback,null,2)})}/>{s.feedback.map(f=><View key={f.id} style={st.card}><Text style={st.text}>{f.detail}</Text></View>)}<Text style={st.note}>Feedback stays on the phone until you choose to share.</Text></>;
}}
return <SafeAreaProvider><SafeAreaView style={st.root}><StatusBar style="light"/><View style={st.header}><Text style={st.logo}>We<Text style={{color:'#c7f95c'}}>Wrap</Text> ↗</Text><Text style={st.label}>MOBILE BETA · 0.3</Text></View><ScrollView horizontal style={st.tabs} contentContainerStyle={{gap:8,paddingHorizontal:16}} showsHorizontalScrollIndicator={false}>{tabs.map(n=><Pressable key={n} accessibilityRole="button" onPress={()=>go(n)} style={[st.tab,page===n&&{backgroundColor:'#c7f95c'}]}><Text style={[st.text,page===n&&{color:'#172014'}]}>{n}</Text></Pressable>)}</ScrollView><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={st.content}><Text style={st.heading}>{page}.</Text>{ready?content():<Text style={st.note}>Loading your workshop…</Text>}</ScrollView></SafeAreaView></SafeAreaProvider>;
}
const st=StyleSheet.create({root:{flex:1,backgroundColor:'#101315'},header:{padding:18,borderBottomWidth:1,borderColor:'#303637',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},logo:{fontSize:27,fontWeight:'800',color:'#fff'},tabs:{flexGrow:0,maxHeight:58,marginVertical:12},tab:{padding:12,borderRadius:8,backgroundColor:'#242a2b'},content:{padding:18,paddingBottom:60},heading:{fontSize:30,fontWeight:'700',color:'#edf0e8',marginBottom:18},title:{fontSize:18,fontWeight:'700',color:'#edf0e8',marginVertical:10},text:{color:'#e8ebe5',fontSize:15},label:{color:'#a6b0a7',fontSize:12},field:{marginBottom:14},input:{color:'#e8ebe5',backgroundColor:'#1b2021',padding:13,borderRadius:8,borderWidth:1,borderColor:'#38403c',marginTop:6},button:{padding:14,borderRadius:9,backgroundColor:'#c7f95c',marginVertical:6},buttonText:{color:'#172014',fontWeight:'700'},card:{padding:16,backgroundColor:'#1b2021',borderWidth:1,borderColor:'#303637',borderRadius:12,marginVertical:10},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:14,borderBottomWidth:1,borderColor:'#303637'},hero:{padding:24,backgroundColor:'#222b21',borderRadius:16,marginBottom:20},heroTitle:{color:'#edf0e8',fontSize:33,fontWeight:'800',marginVertical:20},graffiti:{color:'#849749',fontSize:17,fontWeight:'900',fontStyle:'italic',transform:[{rotate:'-6deg'}],marginBottom:18},eyebrow:{color:'#c7f95c',fontSize:11,letterSpacing:2},note:{color:'#b3b99b',fontSize:12,lineHeight:19,marginVertical:14},swatch:{height:50,borderRadius:7,marginBottom:12},preview:{height:260,backgroundColor:'#263026',borderRadius:14,overflow:'hidden',alignItems:'center',justifyContent:'center',marginVertical:12},photo:{height:230,width:'100%',resizeMode:'contain'},caption:{position:'absolute',bottom:10,color:'#d4ecc2',fontSize:10}});
